version: "3"
services:
  hub:
    image: selenium/hub:3.14
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.14
    environment:
      - HUB_HOST=hub
    depends_on:
      - hub
  firefox:
    image: selenium/node-firefox:3.14
    environment:
      - HUB_HOST=hub
    depends_on:
      - hub